### PR TITLE
ENYO-792: Adding ItemOverlay and ItemOverlaySupport

### PR DESCRIPTION
**Pull request by KunmyonChoi**
Issue:
Adding new kind to support item overlay layout.

DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

### CODE REVIEW

**Comment by KunmyonChoi** [comment]
@aarontam , It looks like my PR is not easy to handle here. Do you want me to create new clean PR from latest upkeep branch?

**Comment by aarontam** [comment]
Hi @KunmyonChoi, yes please. :)

**Comment by KunmyonChoi** [comment]
My pleasure!

**Comment by KunmyonChoi** [comment]
Created new PR for this issue. https://github.com/enyojs/moonstone/pull/1922

**Pull request closed without merging**
