### PR TITLE
ENYO-2411 IntegerPicker does not update range at creation

### PR DESCRIPTION
**Pull request by dragongears**
Enyo-DCO-1.1-Signed-off-by: Art Dahm art.dahm@lge.com

### CODE REVIEW

**Comment by ryanjduffy** [comment]
`range` isn't public; it's private. See [L243](https://github.com/enyojs/moonstone/blob/2.6.0-dev/src/IntegerPicker/IntegerPicker.js#L243). Also, while the range isn't calculated during `create`, it is called by `rendered()`. What's the actual bug here?

**Comment by dragongears** [comment]
I missed that it was being calculated in rendered(). This is probably a non-bug then. Is there a reason it's being done in rendered() instead of create()? Does it have something to do with the (width) buffer?

**Comment by ryanjduffy** [comment]
I don't see an obvious reason. No part of the logic (now at least) requires the node to exist. I tracked it back to being there in Sept 2013 so it predates me by quite a bit.

**Comment by dragongears** [comment]
Which node are you talking about? The buffer? It confused me for a little while then I realized that it's to keep the control's pink background at a constant width while the width of the numbers change.

**Comment by ryanjduffy** [comment]
Any node, afaik. I didn't see anything in `rangeChanged` or the methods it calls that needed a node to exist.

**Pull request closed without merging**
