### PR TITLE
ENYO-1225: ProgressButton: Full progress % does not display during transition

### PR DESCRIPTION
**Pull request by anishlg**
### Issue
In the progress button, full progress percentage (100%) never displays. Once reached the progress 90% it is unexpectedly transitions to 'launch'. But expected to show the progress 100% and then translate to 'launch'

### Fix
Called the 'updateProgressPercent()' function when the progress is greater than or equal to 100%

DCO-1.1-Signed-Off-By: Anish TD anish.td@lge.com

### CODE REVIEW

**Comment by KunmyonChoi** [comment]
It looks like minimal change for fixing this issue. Looks good. @anishlg

**Comment by KunmyonChoi** [comment]
Please add sign-off statement at the bottom of the PR.

**Comment by KunmyonChoi** [comment]
@anishlg , It looks okay.

**Comment by webOS101** [comment]
Not accepting PR's against master

**Pull request closed without merging**
