### PR TITLE
ENYO-781: Add a simplified automated accessor to all samples

### PR DESCRIPTION
**Pull request by Djspaceg**
* Former Sample.html is now simply called "All".
* Added a barebones sample loader to ultimately replace all of the HTML files in the samples directory.
* Added a .htaccess file to tell Apache servers how to redirect requests for the (deprecated) HTML files to the new universal Sample.html
 * Included support for directory indexing and index.html detection for super simple accessing.

### CODE REVIEW

**Comment by ryanjduffy** [comment]
Thoughts on making 'All' the default value rather than the 'No Sample Selected' message?

**Comment by Djspaceg** [comment]
@ryanjduffy Yeah, we could do that. Seems friendly.

**Comment by aarontam** [comment]
@Djspaceg I think we'll also need to update package.js to reflect the renaming of Sample.css to All.css.

**Comment by Djspaceg** [comment]
@aarontam Whoops! I'll add/fix that!

**Pull request merged**
