### PR TITLE
Enyo-2034 Close popup using activated method

### PR DESCRIPTION
**Pull request by DavidUM**
Issue
-------
Activate method could not close Popup

Cause
--------
This is a regression issue of modular work.
Added line was missing during modulization.

Fix
----
Restore missing line

Enyo-DCO-1.1-Signed-off-by: David Um david.um@lge.com

### CODE REVIEW

**Comment by webOS101** [comment]
The popup hide call cannot be inside the guard because the active will be false by the time it gets here, unless there's some test case I'm unaware of.

**Comment by DavidUM** [comment]
If you mentioned `active` of contextualPopupButton, it is already updated when `activated()` is called.
Do you mean this?

**Comment by webOS101** [comment]
No, I mean that the fix does not work as implemented because it can never get to the code after you moved it in the last patch.  `inEvent.originator.active` will already be false. If that step is reverted then the code appears to work.

**Comment by webOS101** [comment]
I have rebased the code and tested against other ContextualPopup bugs to be sure we don't encounter any issues.

**Pull request merged**
