### PR TITLE
ENYO-2156-inputMode doesn't take proper classes in moon.Header

### PR DESCRIPTION
**Pull request by rajyavardhanp**
InputHeader classes are moved to Header, as that is the only dependency
for InputHeader.
Enyo-DCO-1.1-Signed-off-by: Rajyavardhan P <rajyavardhan.p@lge.com>

### CODE REVIEW

**Comment by otisnate** [comment]
If you want to remove every css in ```InputHeader.less```, I think it's better to remvoe ```InputHeader.less``` and modify ```package.json``` file

**Comment by rajyavardhanp** [comment]
Hi @otisnate I changed the PR based on your comments. 
Thankyou.

**Comment by aarontam** [comment]
If we're going this route, we should also remove the `moon-input-header` class from `moonstone/InputHeader` as this is already being applied by `moonstone/Header` and we don't want this unnecessarily in multiple locations.

**Comment by webOS101** [comment]
I removed the unneeded class, removed the InputHeader directory.

**Pull request merged**
