### PR TITLE
ENYO-2305: Pepped up the spinner a bit

### PR DESCRIPTION
**Pull request by Djspaceg**
Spinner looks much less lazy now.

_This PR should be profoundly easy to review. Good luck_
so hard

Enyo-DCO-1.1-Signed-off-by: Blake Stephens <blake.stephens@lge.com>

### CODE REVIEW

**Comment by aarontam** [comment]
Did you intentionally include the commit for PLAT-1948? :smile:

**Comment by Djspaceg** [comment]
@aarontam oops!

**Comment by Djspaceg** [comment]
@aarontam updated!

**Comment by aarontam** [comment]
@Djspaceg :+1:

**Pull request merged**
