### PR TITLE
DRD-8143: Fix full screen video player layout when enters from inline pl...

### PR DESCRIPTION
**Pull request by KunmyonChoi**
...ayer

### Issue:
- The fullscreen video player layout is broken when enters from inline player.
- This can be reproduced only when we use inline player inside of panels. Because webkit fullscreen is affected by the layout of parent node.

### Fix:
- Clear overflow, padding and margin of all the ancestor when it is full screen.

DCO-1.1-Signed-Off-By: Kunmyon Choi kunmyon.choi@lge.com

### CODE REVIEW

**Comment by Djspaceg** [comment]
I assume this set of rules is not combined into one set of selectors because of the bugs with combining them? If not, lets stack up these selectors into one rule-set; like below. Lets also add a "standards" rule, which isn't browser-prefixed: `:full-screen-ancestor:not(iframe)`
```
}
:-webkit-full-screen-ancestor:not(iframe),
:-moz-full-screen-ancestor:not(iframe),
:-ms-full-screen-ancestor:not(iframe),
:-o-full-screen-ancestor:not(iframe),
:full-screen-ancestor:not(iframe) {
  position: absolute !important;
  overflow: visible !important;
  padding: 0 !important;
  margin: 0 !important;
  width: 100% !important;
  height: 100% !important;
}
```

**Comment by KunmyonChoi** [comment]
@Djspaceg , split out rules and add standard rule. Done :)

**Comment by KunmyonChoi** [comment]
Actually stacking up as one rule is not work in this case.

**Comment by Djspaceg** [comment]
That's what I was afraid of. These pseudo/fullscreen selectors are "grouchy".

**Comment by aarontam** [comment]
I *think* the reason stacking doesn't work is because anytime an unrecognized selector is encountered, the browser ignores the associated declaration block.

Also, closing in favor of https://github.com/enyojs/moonstone/pull/2106.

**Comment by Djspaceg** [comment]
That would make sense! Thx @aarontam

**Pull request closed without merging**
