### PR TITLE
ENYO-1194 Set HW acceleration to actual animation element in marqueeText

### PR DESCRIPTION
**Pull request by yeram**
Modify target element that will be accelerated from 'this' to 'this.$.marqueeText'.

### CODE REVIEW

**Comment by aarontam** [comment]
Hi @yeram, thanks for the fix. I was wondering if you had verified whether or not the issue addressed by https://github.com/enyojs/moonstone/commit/27edfcb1f86544c6dc5e508c4af99c1a863f8eb3 is still resolved with your change? If not, we can verify - I was just curious. Thanks!

**Comment by yeram** [comment]
Hi @aarontam, thanks for the review. I will check with @sbcho about your concern.

**Comment by sbcho** [comment]
I'v verified BHV-11438 is not reproduced after applying this commit :)

**Comment by sbcho** [comment]
Could you share

**Comment by yeram** [comment]
Guys, we verified original issue doesn't happened with this change. Thanks!

**Comment by aarontam** [comment]
Awesome, thanks for checking!

**Comment by ryanjduffy** [comment]
Closing for 2.6.0-dev fix

**Pull request closed without merging**
